version: '3'

services:
  # Serviço para o Banco de Dados 
  postgres:
    image: bitnami/postgresql
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRESQL_USERNAME=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_DATABASE}


